# 1.Print 'Hello HCIA'.

In [ ]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [ ]:
a = 2
b = 3
print(a+b)

5


# 3.Define a list and replicate in three different ways.

In [1]:
import copy

#Method one:
list1=["dog","cat"]
new_list1 = list1[:]
print(new_list1)
print(list1)

#Method two:
new_list2 = list(list1)
print(new_list2)

#Method three:
new_list3 = copy.copy(list1)
print(new_list3)

['dog', 'cat']
['dog', 'cat']
['dog', 'cat']
['dog', 'cat']


# 4.Define two lists and merge them together.

In [2]:
listone = ["dog","cat"]
listtwo = ["red","blue"]
mergedlist = listone + listtwo
print(mergedlist)

['dog', 'cat', 'red', 'blue']


# 5. Get the last element of the list and print it.

In [14]:
a = [50, 40, 5555, 236, 789, 1]
a[len(a)-1]


1

# 6.Define a tuple that contains only one element.

In [18]:
a1=(1,)
print(a1)

(1,)


# 7.Define a three-line long string.

In [17]:
a2 = '''
Я люблю котов.
Я люблю собак.
Я люблю птиц. 
'''
print(a2)


Я люблю котов.
Я люблю собак.
Я люблю птиц. 



# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [20]:
a3=("dog",5,100,'cat')
for i in a3:
    print(i)

dog
5
100
cat


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [21]:
def Mul(x,y):
  return x*y
Mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [22]:
import numpy as np 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [23]:
import numpy as np 
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [27]:
x = np.arange(15)
print(x)
x1 = x.reshape(3,5)
x1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [32]:
import numpy as np

A = [[0,1],[85,93]]
B = [[89,55],[8,9]]
np.matmul(A,B)

array([[   8,    9],
       [8309, 5512]])